---
- hosts: debian_servers
  become: yes
  tasks:
    - name: Update packages on Debian servers
      apt:
        name: "apt"
        state: latest
      register: debian_updates
        
    - name: Reboot Debian servers if needed
      reboot:
        reboot_timeout: 300
      when: debian_updates.changed
