---
- name: Update Linux Servers
  hosts: linux_servers
  become: yes
  tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
    
    - name: Update all packages to the latest version
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
